"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as message_constants
from six import python_2_unicode_compatible


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h6$j*o7*qxn*f1fadamxtf=rw2tlr3=vz7@t!3*r-sngy_s+5%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #administrador interfaz
    'admin_interface',
    'colorfield',
    #Clases incluidas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #formularios
    #'multiselectfield',
    'betterforms',
    'crispy_forms',
    'materializecssform',
    #Notificaciones
    'webpush',
    'django_twilio',

    #mi app
    'apps.Almacen',
    'import_export',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'
IMPORT_EXPORT_USE_TRANSACTIONS = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'Smart',
        'USER':'postgres',
        'PASSWORD':'fairyoak2*',
        'HOST':'localhost',
        'PORT': 5432,


    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-eu'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
#Configuarion de email
EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=""
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST_PASSWORD=""


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'static')
#]

MEDIA_URL = '/media/'
STATIC_ROOT= os.path.join(BASE_DIR,'static')
MEDIA_ROOT= os.path.join(os.path.dirname(BASE_DIR),"media_root")

LOGIN_REDIRECT_URL='sesion'

CRISPY_INSTALLED_PACK= 'bootstrap4'

MESSAGE_TAGS={
    message_constants.DEBUG:'debug',
    message_constants.INFO:'info',
    message_constants.SUCCESS:'success',
    message_constants.WARNING:'warning',
    message_constants.ERROR:'danger',

}


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BDnAlD2XMsaUD0AGYgpNnlGnVKTHegSv9-KOFt5jrs9s67htwz2pb5xhX5rC9AJMXZUhvhdFLkiOwPlysfTnwFA",
    "VAPID_PRIVATE_KEY": "cl0Xc5J9VuhltI3sd_mKrkyFjGCxzxOmHsvUwPFvq_E",
    "VAPID_ADMIN_EMAIL": "michellecharles373@gmail.com"
}
TWILIO_ACCOUNT_SID = 'AC6882f5c66eedb6b8a6e733b24df48618'
TWILIO_AUTH_TOKEN = '70a0acdeae855e8f4843b735c8a48de2'
DJANGO_TWILIO_BLACKLIST_CHECK = True
DJANGO_TWILIO_FORGERY_PROTECTION = False

