# Generated by Django 3.1.4 on 2020-12-22 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('nombre_Area', models.CharField(choices=[('JUR', 'juridico'), ('RH', 'RecursosHumanos'), ('CEC', 'CEC'), ('Pro', 'Proyectos'), ('INC', 'Ingeniería de costos'), ('DIR', 'Direccion'), ('SIS', 'Sistemas'), ('SAP', 'SAP'), ('Adm', 'Administracion'), ('Aud', 'Auditoria'), ('Com', 'Compras'), ('Cns', 'Concesiones'), ('Con', 'Contabilidad'), ('Cnt', 'Contraloria'), ('Fis', 'Fiscal'), ('Ctr', 'Control'), ('MCo', 'Manejo de contrato'), ('PVV', 'Provivan'), ('SUB', 'Subcontratos')], max_length=30, primary_key=True, serialize=False)),
                ('piso', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('no_Serie_Cel', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Cel', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Cel', models.CharField(max_length=30, verbose_name='Modelo')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
            },
        ),
        migrations.CreateModel(
            name='Clave_Impresion',
            fields=[
                ('clave', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Clave de impresión',
                'verbose_name_plural': 'Claves de impresión',
            },
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('no_Serie_Co', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de serie')),
                ('nombre_Co', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_com', models.CharField(max_length=30, verbose_name='Modelo')),
                ('tipo_com', models.CharField(choices=[('pce', 'pcescritorio'), ('lap', 'lap')], max_length=3, verbose_name='Tipo')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('Ram', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB')], max_length=5, null=True)),
                ('Disco_Duro', models.CharField(choices=[('500Gb', '500Gb'), ('1TB', '1TB'), ('1.5TB', '1.5TB'), ('2TB', '2TB'), ('2.5TB', '2.5TB'), ('3TB', '3TB')], max_length=6, null=True, verbose_name='Disco Duro')),
                ('Procesador', models.CharField(max_length=20, null=True)),
                ('Ano', models.IntegerField(null=True, verbose_name='Año')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_Empleado', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_Emp', models.CharField(max_length=30, null=True, verbose_name='Nombre')),
                ('ApellidoP_Emp', models.CharField(max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('ApellidoM_Emp', models.CharField(max_length=30, null=True, verbose_name='Apellido Materno')),
                ('puesto', models.CharField(max_length=30)),
                ('Office', models.CharField(choices=[('O365', 'Office365'), ('Win7', 'Windows7')], max_length=4)),
                ('correo_Emp', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('telefono', models.BigIntegerField()),
                ('ext', models.IntegerField(verbose_name='Extensión')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Eq_Vid',
            fields=[
                ('no_Serie_Vid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Vid', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Vid', models.CharField(max_length=30, verbose_name='Modelo')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name': 'Equipo de video',
                'verbose_name_plural': 'Equipo de video',
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('no_Serie_Im', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Im', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Im', models.CharField(max_length=30, verbose_name='Modelo')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Multifuncional',
            fields=[
                ('no_Serie_Mul', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Mul', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Mul', models.CharField(max_length=30, verbose_name='Modelo')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name': 'Multifuncional',
                'verbose_name_plural': 'Multifuncionales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('Id_proyecto', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('no_Serie_Pro', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Pro', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Pro', models.CharField(max_length=30, verbose_name='Modelo')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name': 'Proyector',
                'verbose_name_plural': 'Proyectores',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('no_Serie_Rad', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='No. de Serie')),
                ('nombre_Rad', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10)),
                ('modelo_Cel', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Status', models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('no_Serie_Te', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_Te', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=10)),
                ('tipo_entrada', models.CharField(choices=[('usb', 'usb'), ('PS/2', 'PS/2')], max_length=4)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('computadora', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Almacen.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Emp', models.CharField(max_length=30, verbose_name='Nombre')),
                ('ApellidoP_Emp', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('ApellidoM_Emp', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('tipo_com', models.CharField(choices=[('pce', 'pcescritorio'), ('lap', 'lap')], max_length=3, verbose_name='Tipo de computadora')),
                ('Office', models.CharField(choices=[('O365', 'Office365'), ('Win7', 'Windows7')], max_length=4)),
                ('teclado', models.CharField(choices=[('aplica', 'aplica'), ('no aplica', 'no aplica')], max_length=15)),
                ('monitor', models.CharField(choices=[('aplica', 'aplica'), ('no aplica', 'no aplica')], max_length=15)),
                ('Status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('En proceso', 'En proceso'), ('Atendida', 'Atendida')], max_length=15)),
                ('Fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de entrega de equipo')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.area')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.proyecto')),
            ],
            options={
                'verbose_name': 'Solicitud de Equipo',
                'verbose_name_plural': 'Solicitud de Equipo',
            },
        ),
        migrations.CreateModel(
            name='Proyecto_empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.proyecto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Empledos por proyecto',
                'verbose_name_plural': 'Empledos por proyecto',
            },
        ),
        migrations.CreateModel(
            name='Prestamo_Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('Radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.radio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Prestamos de Radios',
                'verbose_name_plural': 'Prestamos de Radios',
            },
        ),
        migrations.CreateModel(
            name='Prestamo_Impresoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('Impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.impresora')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Prestamos de Impresoras',
                'verbose_name_plural': 'Prestamos de Impresoras',
            },
        ),
        migrations.CreateModel(
            name='Prestamo_Eq_Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('Eq_Video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.eq_vid', verbose_name='Equipo de video')),
                ('Multifuncional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.multifuncional')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.proyecto')),
                ('Proyector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.proyector')),
                ('Responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Prestamos de Equipo de video',
                'verbose_name_plural': 'Prestamos de Equipo de video',
            },
        ),
        migrations.CreateModel(
            name='Prestamo_Computadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.computadora')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Prestamos de computadoras',
                'verbose_name_plural': 'Prestamos de computadoras',
            },
        ),
        migrations.CreateModel(
            name='Prestamo_Celular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.celular')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
            ],
            options={
                'verbose_name': 'Prestamos de Celulares',
                'verbose_name_plural': 'Prestamos de Celulares',
            },
        ),
        migrations.CreateModel(
            name='Peticion_Impresiones_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Emp', models.CharField(max_length=30, verbose_name='Nombre')),
                ('ApellidoP_Emp', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('ApellidoM_Emp', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('saldo', models.PositiveIntegerField()),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de entrega de equipo')),
                ('Clave', models.ManyToManyField(to='Almacen.Clave_Impresion')),
            ],
            options={
                'verbose_name': 'Petición de impresiones',
                'verbose_name_plural': 'Peticiones de impresiones',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('no_Serie_Mo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_Mo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=10)),
                ('tipo_entrada', models.CharField(choices=[('usb', 'usb'), ('PS/2', 'PS/2')], max_length=4)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('computadora', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Almacen.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('no_Serie_Pa', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_Pa', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('computadora', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Almacen.computadora')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.AddField(
            model_name='clave_impresion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado'),
        ),
    ]
