# Generated by Django 3.1.3 on 2020-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyector',
            options={'verbose_name': 'Proyector', 'verbose_name_plural': 'Proyectores'},
        ),
        migrations.AddField(
            model_name='proyector',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
