# Generated by Django 3.1.4 on 2021-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion_impresiones_color',
            name='Status',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('En proceso', 'En proceso'), ('Atendida', 'Atendida')], default='Solicitado', max_length=15),
        ),
    ]
