# Generated by Django 3.1.4 on 2021-01-03 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Almacen', '0002_peticion_impresiones_color_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Emp', models.CharField(max_length=30, verbose_name='Nombre')),
                ('ApellidoP_Emp', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('ApellidoM_Emp', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('clasificacion_equipo', models.CharField(choices=[('CPU', 'CPU'), ('LAPTOP', 'LAPTOP'), ('TelefoniaIP', 'TelefoníaIP'), ('Celular', 'Celular')], max_length=15, verbose_name='Equipo')),
                ('tipo_atencion', models.CharField(choices=[('Telefónica', 'Telefónica'), ('Remota', 'Remota'), ('Presencial', 'Presencial'), ('Equipo_video', 'Equipo_video'), ('Implersora', 'Impresora')], max_length=15, verbose_name='Tipo de atención')),
                ('dano_fisico', models.CharField(choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='El equipo presenta daño por uso o descuido', max_length=10, verbose_name='Daño físico')),
                ('retirar', models.CharField(choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='¿Se retiró el equipo?', max_length=10, verbose_name='Retirar equipo')),
                ('codigo_error', models.CharField(choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='¿Presenta código de error?', max_length=10)),
                ('solucion', models.CharField(choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='¿Se soluciono la incidencia?', max_length=10, verbose_name='Solucion')),
                ('fecha_inicidencia', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField()),
                ('reporte_usuario', models.TextField(blank=True, help_text='Indique detalladamente su problema', verbose_name='Descripción de la incidencia')),
                ('reporte_resolucion', models.TextField(blank=True, help_text='Indique detalladamente la resolución del problema', verbose_name='Descripción de la solución')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Obsevaciones')),
                ('Status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('En proceso', 'En proceso'), ('Atendida', 'Atendida')], default='Solicitado', max_length=15)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.area')),
                ('Atencion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero Responsable')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.proyecto')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Ordenes de servicio',
            },
        ),
    ]
