# Generated by Django 3.1.3 on 2020-11-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Almacen', '0003_auto_20201124_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ApellidoM_Emp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ApellidoP_Emp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='correo_Emp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre_Emp',
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
