# Generated by Django 3.1.4 on 2021-01-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_ordenes_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='clasificacion_equipo',
            field=models.CharField(choices=[('CPU', 'CPU'), ('LAPTOP', 'LAPTOP'), ('TelefoniaIP', 'TelefoníaIP'), ('Celuslar', 'Celular')], max_length=15, verbose_name='Equipo'),
        ),
    ]
