# Generated by Django 3.1.3 on 2020-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_auto_20201125_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ApellidoM_Emp',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ApellidoP_Emp',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo_Emp',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_Emp',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
    ]
