# Generated by Django 3.1.4 on 2021-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_auto_20210102_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='Status',
            field=models.CharField(blank=True, choices=[('Solicitado', 'Solicitado'), ('En proceso', 'En proceso'), ('Atendida', 'Atendida')], default='Solicitado', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='clasificacion_equipo',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('LAPTOP', 'LAPTOP'), ('TelefoniaIP', 'TelefoníaIP'), ('Celuslar', 'Celular')], max_length=15, null=True, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='codigo_error',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='¿Presenta código de error?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='dano_fisico',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='El equipo presenta daño por uso o descuido', max_length=10, null=True, verbose_name='Daño físico'),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='reporte_resolucion',
            field=models.TextField(blank=True, help_text='Indique detalladamente la resolución del problema', null=True, verbose_name='Descripción de la solución'),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='reporte_usuario',
            field=models.TextField(blank=True, help_text='Indique detalladamente su problema', null=True, verbose_name='Descripción de la incidencia'),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='retirar',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no'), ('no aplica', 'no aplica')], help_text='¿Se retiró el equipo?', max_length=10, null=True, verbose_name='Retirar equipo'),
        ),
        migrations.AlterField(
            model_name='ordenes_servicio',
            name='tipo_atencion',
            field=models.CharField(blank=True, choices=[('Telefónica', 'Telefónica'), ('Remota', 'Remota'), ('Presencial', 'Presencial')], max_length=15, null=True, verbose_name='Tipo de atención'),
        ),
    ]
