# Generated by Django 3.1.4 on 2021-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0005_auto_20210102_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_equipo',
            name='Aplicaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
