# Generated by Django 3.1.4 on 2021-01-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Almacen', '0006_solicitud_equipo_aplicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_directo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('creacio', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
