# Generated by Django 3.1.4 on 2021-01-04 16:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0007_contacto_directo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto_directo',
            options={'verbose_name': 'Contactos de soporte técnico', 'verbose_name_plural': 'Contactos de soporte técnico'},
        ),
        migrations.RemoveField(
            model_name='contacto_directo',
            name='creacio',
        ),
        migrations.AlterField(
            model_name='contacto_directo',
            name='numero_celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de celular'),
        ),
    ]
