# Generated by Django 3.1.4 on 2021-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0008_auto_20210104_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='piso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='Status',
            field=models.CharField(choices=[('disponible', 'disponible'), ('servicio', 'servicio'), ('reparacion', 'reparación'), ('destruccion', 'destruccion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='tipo_com',
            field=models.IntegerField(choices=[(1, 'pcescritorio'), (2, 'laptop')], default=1),
        ),
    ]
